### ISSUE TITLE
try LADP , scmadmin unusable

### ISSUE THREAD

**Issue by SaboShao** [scm-manager/scm-manager#1188]
I tried to connect a windows ldap, it is not successful and the default use scmadmin could not login .
How can I clean the ldap config and use scmadmin login again?
BTW, maybe some details docs for LDAP configuration will be needed.

**Comment by eheimbuch** [comment]
Hey SaboShao,

you have to delete the ldap.xml in the config directory of your SCM-Manager instance and afterwards restart the instance. This should do the trick to login with scmadmin again.

Regarding the documentation you are right, that we are still missing useful docs for the SCM-Ldap-Plugin. It should be added soon, since we regularly improve our documentation.

**Comment by SaboShao** [comment]
Thanks eheimbuch
