### ISSUE TITLE
Raw access to mercurial API in 2.0

### ISSUE THREAD

**Issue by fnajera-rac-de** [scm-manager/scm-manager#1560]
I have a number of URLs that were working in SCM Manager 1.x:

https://server/hg/repository-name/raw-file/default/folder/file.txt
https://server/hg/repository-name/raw-file/default/ 
https://server/hg/repository-name/raw-file/18292a410000/folder/file.txt
https://server/hg/repository-name/raw-file/18292a410000/
https://server/hg/repository-name/rev/18292a410000?style=json
https://server/hg/repository-name/tags?style=json
https://server/hg/repository-name/branches?style=json

With them we can get the raw contents of any file or folder in any revision, the log of a given revision, and the list of tags and branches.

We access these URLs programmatically as part of our build process and toolchain.

None of these URLs seem to work in SCM Manager 2.x, and I cannot find how to adapt them so that it works.

How can I get this functionality working in SCM Manager 2.x?

**Comment by sdorra** [comment]
In SCM-Manager we want to use the same url for the protocol (push/pull) and the ui. To archive this goal we have to decide which client is routed to hgweb (protocol client) and which is routed to ui. The urls you have mentioned are urls from hgweb and my assumption is that your requests are routed to the ui instead of the protocol endpoint. You have now two options to get the requested informations.

1. Use the rest api of scm-manager. This has the advantage that it works with all repository types and not only with mercurial. For more information about the rest api have a look at the [scm-openapi-plugin](https://scm-manager.org/plugins/scm-openapi-plugin/docs/1.0.x/en/usage/).
2. Make the SCM manager believe that your request comes from a Mercurial client e.g.:

```bash
▶ curl -u scmadmin -H "User-Agent: Mercurial" http://myscminstance/scm/repo/namespace/name/raw-file/default/
```

**Comment by fnajera-rac-de** [comment]
Thank you! We tries the user agent tip and it works perfectly.
