### ISSUE TITLE
Disable GIT & HG plugins 

### ISSUE THREAD

**Issue by legos765** [scm-manager/scm-manager#1706]
Hello,
In the previous (1.60) version it was available via removing the jar from webapp.war

``zip -d /opt/scm-server/var/webapp/scm-webapp.war WEB-INF/lib/scm-git-plugin-*.jar``

I would like to disable built-in git and hg plugins during startup of scm-manager 2.18.0.
Do you know if it is possible?

**Comment by eheimbuch** [comment]
Hey @legos765,

Theoretically it should be possible to disable some core plugins. If you check out the git config you may disable git via the rest api. Your PUT request to "/v2/git/config" could look like this:

```
{
  "disabled": true,
  "gcExpression": null,
  "nonFastForwardDisallowed": false,
  "defaultBranch": "main"
}
```

BUT this is only theoretically, since we do not support this feature officially yet. It is highly probable your SCM-Manager UI will break on some pages / features.

I don't know if a "right" way to do this exists yet. We will discuss your request in our team. 

Best regards,
Eduard Heimbuch

**Comment by legos765** [comment]
Hi @eheimbuch 

I've tested your solution and it looks pretty good. Unless there is no git repository, no scm error pops up and when creating a new repo from the list, only subversion is shown to me.

If there is already a git repo, there are problems and the repo tab is not displayed:

![Capture23](https://user-images.githubusercontent.com/57687583/125055706-c8ebf800-e0a7-11eb-8dcd-0c5cb08267aa.JPG)

but of course it would be a weird case if I wanted to disable the git plugin and still keep the git repo.

So for me, you provided effective solution, thank you @eheimbuch !

**Comment by eheimbuch** [comment]
Glad i could help you. Then i will close this issue.
