### ISSUE TITLE
User rights report

### ISSUE THREAD

**Issue by Shaoranlaos** [scm-manager/scm-manager#1724]
#### Problem to be solved

When you delete a user you can not find out where this user is configured.
This will lead to a cluttering of the rights pages on the repositories or in the members page of a group.
(I had to delete 5 users which each had very different repository accesses and am not a hundert percent sure if i got all the repositories.)

That the rights could be existing even if the user is delete is not realy a problem but it could lead to a bit of confusion if you are seeing it some month after the user already left the company.

#### Proposed solution

It would be good to have a report where you (as administrator) can see where a user is configured, be it as a group member or with direct privileges on a repository.

It could probably also make sense to provide the same for a group to see where a group has privileges,

**Comment by eheimbuch** [comment]
Hello @Shaoranlaos 

We have discussed a very similar suggestion some time ago. It is technically very difficult as an administrator to find out what permissions a particular user has. This is because the permissions for a user are collected from various sources like external groups, internal groups, repository permissions, namespace permissions and direct permissions.

But we see your use case and will discuss this again to see what solution we can come to.

**Comment by eheimbuch** [comment]
We discussed this feature. We will try to show all permissions of a user (without external groups!). We have included this feature in the SCM-Manager roadmap.

**Comment by eheimbuch** [comment]
This feature was released with version 2.42.0

Read the related blog post: https://scm-manager.org/blog/posts/2023-02-17-scm-manager-2-42-x/#overview-for-permissions
