### ISSUE TITLE
Read protection

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#346]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/346) by Anonymous.**

----------------------------------------

Good Morning Sebastian,

Is it possible to you create a plugin similar to scm-pathwp-plugin?
I need a plugin that adds read protection for repositories.

I am awaiting...

Thank you very much!!!

**Comment by jpylypiw** [comment]
I have to reopen this, because this feature is important.
Subversion is currently the only scm that supports read protection of directories and scm-manager is the only system that has a usable webinterface.
Is there a possability to implement this feature (as a plugin for example) in the next release cycles?
