### ISSUE TITLE
unlimited grouping

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#527]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/527) by Matthias Schwellenberg (Bitbucket: [mschwell](https://bitbucket.org/mschwell), GitHub: [mschwell](https://github.com/mschwell)).**

----------------------------------------

When using plenty repositories the 1-level-grouping isn't enough to keep a clear view. Currently we use deeper directory structures on the server, e.g.

/scm/git/path/to/repository1
/scm/git/path/to/repository2
/scm/git/path/to/repository3
/scm/git/path/2/repository1
/scm/git/path/2/repository2
....

but the grouping feature in the web interface only shows two groups named "path/to" and "path/2" and is not able to display this structure.

We would assume the interface to display only one top-level group "path" with two sub-groups "to" and "2" and so on.

**Comment by sdorra** [comment]
We have decided to remove the grouping feature for scm-manager 2, because it comes with a lot of technical problems. In v2 there is a namespace and the name of the repository.

**Comment by dhs-rec** [comment]
So this was closed because the thing got a new name? But the problem still persists, right? Namespaces can't be nested (even the user defined ones).

**Comment by sdorra** [comment]
@dhs-rec we decided to drop the groups feature of scm-manager 1.x in favour of namespaces. Namespaces have a fixed depth in contrast to the groups feature. We made this decision, because the infinite groups makes it very difficult to distinguish between protocol, api and repository urls. The fixed depth of the namespaces have made features possible, such as using the same url for the protocol (clone, pull and push) and the ui.

For what purpose do you need nested namespaces? Do you need the feature to organize your repositories in the ui or do you want depth repository urls?

**Comment by dhs-rec** [comment]
It's for organizational purposes (for example department/group/purpose/repo). But also for access control at any level, incl. inheritance). And finally for making the migration from both GitLab and HGweb served repositories easier for us and our users,
